version: '3'

services:
  ui:
    build:
      context: ./
      target: prod
    ports:
      - '80:80' # Deben ser los mismos puertos, sino, la página se refresca constantemente
    container_name: app
    volumes:
      - '/usr/src/app/node_modules' # Necesario para el arranque de la app en Docker
      - '.:/usr/src/app'

  api:
    container_name: app-api
    image: 'ivaantorres/api-real-time-chat-app:0.1'
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - '3000:3000'

  mongo:
    image: 'mongo:5.0.6'
    ports:
      - '27017:27017'
    container_name: mongo
    volumes:
      - '/c/data/db:/data/db'
    logging:
      driver: none
