version: '3'

services:
  ui:
    container_name: app-ui
    build:
      context: ./
      target: dev
    ports:
      - '80:80' # Deben ser los mismos puertos, sino, la página se refresca constantemente
    volumes:
      - '/usr/src/app/node_modules' # Necesario para el arranque de la app en Docker
      - '.:/usr/src/app'

  api:
    container_name: app-api
    image: 'ivaantorres/api-real-time-chat-app:${API_VERSION}'
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=thunder-link
      - PORT=${VITE_API_PORT}
    ports:
      - '${VITE_API_PORT}:${VITE_API_PORT}'

  mongodb:
    container_name: mongo
    image: 'mongo:5.0.6'
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - '/c/data/db:/data/db'
    logging:
      driver: none

  sonarqube:
    container_name: sonarqube
    image: 'sonarqube:lts-community'
    ports:
      - '${SONAR_UI_PORT}:9000'
      - '9002:9002'
    volumes:
      - '/c/Users/Iván/Desktop/sonarqube/data:/opt/sonarqube/data'
      - '/c/Users/Iván/Desktop/sonarqube/conf:/opt/sonarqube/conf'
      - '/c/Users/Iván/Desktop/sonarqube/logs:/opt/sonarqube/logs'
      - '/c/Users/Iván/Desktop/sonarqube/extensions:/opt/sonarqube/extensions'
    logging:
      driver: none

networks: 
  default:
    name: thunder-link-network