// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoardInfo: typeof import('./components/BoardInfo/BoardInfo.vue')['default']
    BoardUsers: typeof import('./components/BoardUsers/BoardUsers.vue')['default']
    Chat: typeof import('./components/Chat/Chat.vue')['default']
    ConnectionStatus: typeof import('./components/ConnectionStatus/ConnectionStatus.vue')['default']
    FormDashboard: typeof import('./components/FormDashboard/FormDashboard.vue')['default']
    Loader: typeof import('./components/Loader/Loader.vue')['default']
    Message: typeof import('./components/Message/Message.vue')['default']
    Tag: typeof import('./components/Tag/Tag.vue')['default']
  }
}

export { }
