// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./components/Chat/Chat.vue')['default']
    FormDashboard: typeof import('./components/FormDashboard/FormDashboard.vue')['default']
    Loader: typeof import('./components/Loader/Loader.vue')['default']
    Message: typeof import('./components/Message/Message.vue')['default']
  }
}

export { }
