// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoardInfo: typeof import('./components/BoardInfo.vue')['default']
    BoardUsers: typeof import('./components/BoardUsers.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    ConnectionStatus: typeof import('./components/ConnectionStatus.vue')['default']
    FormDashboard: typeof import('./components/FormDashboard.vue')['default']
    LangIcon: typeof import('./components/icons/LangIcon.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    SelectButton: typeof import('./components/SelectButton.vue')['default']
    SendMessageIcon: typeof import('./components/icons/SendMessageIcon.vue')['default']
    SwitchButton: typeof import('./components/SwitchButton.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
  }
}

export { }
